/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PersonnalisationRouteImport } from './routes/personnalisation'
import { Route as MetiersRouteImport } from './routes/metiers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonnalisationRoute = PersonnalisationRouteImport.update({
  id: '/personnalisation',
  path: '/personnalisation',
  getParentRoute: () => rootRouteImport,
} as any)
const MetiersRoute = MetiersRouteImport.update({
  id: '/metiers',
  path: '/metiers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/metiers': typeof MetiersRoute
  '/personnalisation': typeof PersonnalisationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/metiers': typeof MetiersRoute
  '/personnalisation': typeof PersonnalisationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/metiers': typeof MetiersRoute
  '/personnalisation': typeof PersonnalisationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogue'
    | '/contact'
    | '/metiers'
    | '/personnalisation'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogue'
    | '/contact'
    | '/metiers'
    | '/personnalisation'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/catalogue'
    | '/contact'
    | '/metiers'
    | '/personnalisation'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogueRoute: typeof CatalogueRoute
  ContactRoute: typeof ContactRoute
  MetiersRoute: typeof MetiersRoute
  PersonnalisationRoute: typeof PersonnalisationRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personnalisation': {
      id: '/personnalisation'
      path: '/personnalisation'
      fullPath: '/personnalisation'
      preLoaderRoute: typeof PersonnalisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metiers': {
      id: '/metiers'
      path: '/metiers'
      fullPath: '/metiers'
      preLoaderRoute: typeof MetiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogueRoute: CatalogueRoute,
  ContactRoute: ContactRoute,
  MetiersRoute: MetiersRoute,
  PersonnalisationRoute: PersonnalisationRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
